<?php

/**
 * PluginacCustomFieldsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginacCustomFieldsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginacCustomFieldsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginacCustomFields');
    }
}